env:
  TERM: xterm-256color

background_opacity: 1.00
draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#0d0d0d'
    # background: '#000000'
    foreground: '#ffffff'
  normal:
    black: '#000000'
    red: '#cc0403'
    green: '#19cb00'
    yellow: '#cecb00'
    blue: '#0d73cc'
    magenta: '#cb1ed1'
    cyan: '#0dcdcd'
    white: '#dddddd'

  bright:
    black: '#767676'
    red: '#f2201f'
    green: '#23fd00'
    yellow: '#ffff00'
    blue: '#1a8fff'
    magenta: '#fd28ff'
    cyan: '#14ffff'
    white: '#ffffff'

cursor:
  style:
    blinking: on

font:
  size: 11
  normal:
    family: "IBM Plex Mono"
    style: Regular
  bold:
    family: IBMPlexMono
    style: Bold
  italic:
    family: IBMPlexMono
    style: Italic
  bold_italic:
    family: IBMPlexMono
    style: Bold Italic

window:
  padding:
    x: 10
    y: 10
